# https://github.com/tensorflow/tfjs/issues/3881
packageExtensions:
  '@tensorflow/tfjs@*':
    peerDependencies:
      seedrandom: '~3.0.5'
  '@tensorflow-models/mobilenet@*':
    peerDependencies:
      '@tensorflow/tfjs-converter': '4.2.0'
